### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by paustian** [paustian/Book#15]
Hooks are not being communicated. I don’t know if this is an issue with Book, Quickcheck or the hook system.

**Comment by craigh** [comment]
Which core are you testing with?

**Comment by paustian** [comment]
1.4.1. Yeah I know I should test against 1.4.2. I do have it working now. I just need to recode some things.

**Comment by paustian** [comment]
It was my issue btw

**Comment by paustian** [comment]
Hooks working and tested against 1.4.2
